In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/atalamahardika/Diabetes-Dataset/refs/heads/main/diabetes.csv')
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
print(f'Baris dan kolom : {df.shape}')

Baris dan kolom : (768, 9)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [6]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [7]:
print(f'Data duplikasi : {df.duplicated().sum()}')

Data duplikasi : 0

In [8]:
df.describe().round(2)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.00,768.00,768.00,768.00,768.00,768.00,768.00,768.00,768.00
mean,3.85,120.89,69.11,20.54,79.80,31.99,0.47,33.24,0.35
std,3.37,31.97,19.36,15.95,115.24,7.88,0.33,11.76,0.48
min,0.00,0.00,0.00,0.00,0.00,0.00,0.08,21.00,0.00
25%,1.00,99.00,62.00,0.00,0.00,27.30,0.24,24.00,0.00
50%,3.00,117.00,72.00,23.00,30.50,32.00,0.37,29.00,0.00
75%,6.00,140.25,80.00,32.00,127.25,36.60,0.63,41.00,1.00
max,17.00,199.00,122.00,99.00,846.00,67.10,2.42,81.00,1.00

In [9]:
df.corr().round(2)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
Pregnancies,1.00,0.13,0.14,-0.08,-0.07,0.02,-0.03,0.54,0.22
Glucose,0.13,1.00,0.15,0.06,0.33,0.22,0.14,0.26,0.47
BloodPressure,0.14,0.15,1.00,0.21,0.09,0.28,0.04,0.24,0.07
SkinThickness,-0.08,0.06,0.21,1.00,0.44,0.39,0.18,-0.11,0.07
Insulin,-0.07,0.33,0.09,0.44,1.00,0.20,0.19,-0.04,0.13
BMI,0.02,0.22,0.28,0.39,0.20,1.00,0.14,0.04,0.29
DiabetesPedigreeFunction,-0.03,0.14,0.04,0.18,0.19,0.14,1.00,0.03,0.17
Age,0.54,0.26,0.24,-0.11,-0.04,0.04,0.03,1.00,0.24
Outcome,0.22,0.47,0.07,0.07,0.13,0.29,0.17,0.24,1.00

In [10]:
# Calculate quartiles and IQR for each column
quartile_data = {}
for col in df.columns:
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    iqr = q3 - q1
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr
    quartile_data[col] = {'q1': q1, 'q3': q3, 'iqr': iqr,
                          'lower_bound': lower_bound, 'upper_bound': upper_bound}

# Convert the dictionary to DataFrame for better readability
quartile_df = pd.DataFrame(quartile_data).transpose()

# Find outliers in each column
outliers = {}
for col in df.columns:
    outliers[col] = []
    for value in df[col]:
        if value < quartile_data[col]['lower_bound'] or value > quartile_data[col]['upper_bound']:
            outliers[col].append(value)

# Combine total outliers and outlier data for each column
for col in df.columns:
    count = len(outliers[col])
    if count > 0:
        print(f"Total outliers in {col}: {count} --> {outliers[col]}")
    else:
        print(f"Total outliers in {col}: {count}")

Total outliers in Pregnancies: 4 --> [15, 17, 14, 14]
Total outliers in Glucose: 5 --> [0, 0, 0, 0, 0]
Total outliers in BloodPressure: 45 --> [0, 0, 30, 110, 0, 0, 0, 0, 108, 122, 30, 0, 110, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 108, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 110, 0, 24, 0, 0, 0, 0, 114, 0, 0, 0]
Total outliers in SkinThickness: 1 --> [99]
Total outliers in Insulin: 34 --> [543, 846, 342, 495, 325, 485, 495, 478, 744, 370, 680, 402, 375, 545, 360, 325, 465, 325, 415, 579, 474, 328, 480, 326, 330, 600, 321, 440, 540, 480, 335, 387, 392, 510]
Total outliers in BMI: 19 --> [0.0, 0.0, 0.0, 0.0, 53.2, 55.0, 0.0, 67.1, 52.3, 52.3, 52.9, 0.0, 0.0, 59.4, 0.0, 0.0, 57.3, 0.0, 0.0]
Total outliers in DiabetesPedigreeFunction: 29 --> [2.288, 1.441, 1.39, 1.893, 1.781, 1.222, 1.4, 1.321, 1.224, 2.329, 1.318, 1.213, 1.353, 1.224, 1.391, 1.476, 2.137, 1.731, 1.268, 1.6, 2.42, 1.251, 1.699, 1.258, 1.282, 1.698, 1.461, 1.292, 1.394]
Total outliers in Age: 9 --> [69, 67, 72, 81, 67, 67, 70, 68, 69]
Total outliers in Outcome: 0

In [11]:
# Remove rows with outliers
original_size = df.shape
for col in df.columns:
    df = df[(df[col] >= quartile_data[col]['lower_bound']) & (df[col] <= quartile_data[col]['upper_bound'])]

# Print size before and after removing outliers
print(f"Data size before removing outliers: {original_size}")
print(f"Data size after removing outliers: {df.shape}")

Data size before removing outliers: (768, 9)
Data size after removing outliers: (639, 9)

## Preprocessing

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 639 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               639 non-null    int64
 1   Glucose                   639 non-null    int64
 2   BloodPressure             639 non-null    int64
 3   SkinThickness             639 non-null    int64
 4   Insulin                   639 non-null    int64
 5   BMI                       639 non-null    float64
 6   DiabetesPedigreeFunction  639 non-null    float64
 7   Age                       639 non-null    int64
 8   Outcome                   639 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 49.9 KB

In [13]:
x = df.drop(columns='Outcome')
y = df['Outcome']

In [14]:
#Import Sampler libraries
from imblearn.combine import SMOTEENN
from imblearn.over_sampling import RandomOverSampler

# for imbalance data
ros = RandomOverSampler(random_state=40)
x_ros, y_ros = ros.fit_resample(x, y)

# SMOTE + ENN
smote_enn = SMOTEENN(random_state=42)
X_resampled_enn, y_resampled_enn = smote_enn.fit_resample(x_ros, y_ros)

In [15]:
X_resampled_enn.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,1,85,66,29,0,26.6,0.351,31
1,1,89,66,23,94,28.1,0.167,21
2,4,110,92,0,0,37.6,0.191,30
3,8,99,84,0,0,35.4,0.388,50
4,1,97,66,15,140,23.2,0.487,22

In [16]:
y_resampled_enn.head()

0    0
1    0
2    0
3    0
4    0
Name: Outcome, dtype: int64

In [17]:
# Buat DataFrame baru dari data yang telah di-resample
resampled_data = pd.concat([X_resampled_enn, y_resampled_enn], axis=1)

In [18]:
resampled_data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,1,85,66,29,0,26.6,0.351,31,0
1,1,89,66,23,94,28.1,0.167,21,0
2,4,110,92,0,0,37.6,0.191,30,0
3,8,99,84,0,0,35.4,0.388,50,0
4,1,97,66,15,140,23.2,0.487,22,0
...,...,...,...,...,...,...,...,...,...
510,0,105,84,0,0,27.9,0.741,62,1
511,2,105,80,45,191,33.7,0.711,29,1
512,9,130,70,0,0,34.2,0.652,45,1
513,1,95,82,25,180,35.0,0.233,43,1
514,3,187,70,22,200,36.4,0.408,36,1

In [21]:
resampled_data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [20]:
resampled_data.to_csv('data/data-cleaned.csv', index=False)